#!/bin/bash

# Script for testing the flow of an asset up until it has been synced with ERDA. No HPC processing or interaction wiht Specify.
# This does leave cleaning up of the asset. It also leaves assets in a state where they can be further processed.

root="/home/dassco/integration/DaSSCo-Integration/IntegrationServer"

nohup python "$root/Ndrive/ndrive_new_files.py" > "$root/Ndrive/ndrive_new_files.out" 2>&1 &
nohup python "$root/Ndrive/process_files_from_ndrive.py" > "$root/Ndrive/process_files_from_ndrive.out" 2>&1 &

nohup python "$root/HealthUtility/flag_paused_status_handler.py" > "$root/HealthUtility/flag_paused_status_handler.out" 2>&1 &
nohup python "$root/HealthUtility/asset_paused_status_handler.py" > "$root/HealthUtility/asset_paused_status_handler.out" 2>&1 &
nohup python "$root/HealthUtility/asset_error_status_handler.py" > "$root/HealthUtility/asset_error_status_handler.out" 2>&1 &

nohup python "$root/StorageUpdater/asset_creator.py" > "$root/StorageUpdater/asset_creator.out" 2>&1 &
nohup python "$root/StorageUpdater/file_uploader.py" > "$root/StorageUpdater/file_uploader.out" 2>&1 &
nohup python "$root/StorageUpdater/sync_erda.py" > "$root/StorageUpdater/sync_erda.out" 2>&1 &
nohup python "$root/StorageUpdater/update_metadata.py" > "$root/StorageUpdater/update_metadata.out" 2>&1 &
nohup python "$root/StorageUpdater/validate_erda_sync.py" > "$root/StorageUpdater/validate_erda_sync.out" 2>&1 &
#nohup python "$root/StorageUpdater/open_share.py" > "$root/StorageUpdater/open_share.out" 2>&1 &
nohup python "$root/StorageUpdater/close_share.py" > "$root/StorageUpdater/close_share.out" 2>&1 &

# logs outputs for each into the folder containing the service - these outputs are not the logs generated by the logging library but print statements in the code