from enum import Enum

class AssetStatusNT(Enum):
    WORKING_COPY = "WORKING_COPY"
    ISSUE_WITH_MEDIA = "ISSUE_WITH_MEDIA"
    ARCHIVE = "ARCHIVE"
    FOR_DELETION = "FOR_DELETION"
    PROCESSING_HALTED = "PROCESSING_HALTED"
    BEING_PROCESSED = "BEING_PROCESSED"
    ISSUE_WITH_METADATA = "ISSUE_WITH_METADATA"