from enum import Enum

class ErdaStatusEnum(Enum):
    COMPLETED = "COMPLETED"
    ASSET_RECEIVED = "ASSET_RECEIVED"
    METADATA_RECEIVED = "METADATA_RECEIVED"
    ERDA_ERROR = "ERDA_ERROR"
    ERDA_SYNCHRONISED = "ERDA_SYNCHRONISED"
    SPECIFY_SYNC_SCHEDULED = "SPECIFY_SYNC_SCHEDULED"
    SPECIFY_SYNCHRONISED = "SPECIFY_SYNCHRONISED"
    SPECIFY_SYNC_FAILED = "SPECIFY_SYNC_FAILED"

class ErdaStatus:
    def __init__(self):
        self.COMPLETED = ErdaStatusEnum.COMPLETED.value
        self.ASSET_RECEIVED = ErdaStatusEnum.ASSET_RECEIVED.value
        self.METADATA_RECEIVED = ErdaStatusEnum.METADATA_RECEIVED.value
        self.ERDA_ERROR = ErdaStatusEnum.ERDA_ERROR.value
        self.ERDA_SYNCHRONISED = ErdaStatusEnum.ERDA_SYNCHRONISED.value
        self.SPECIFY_SYNC_SCHEDULED = ErdaStatusEnum.SPECIFY_SYNC_SCHEDULED.value
        self.SPECIFY_SYNCHRONISED = ErdaStatusEnum.SPECIFY_SYNCHRONISED.value
        self.SPECIFY_SYNC_FAILED = ErdaStatusEnum.SPECIFY_SYNC_FAILED.value